import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createJiti } from "jiti";

const jiti = createJiti(import.meta.url, {
  jsx: true,
  tsconfigPaths: true,
});

const { createTranslator } = await jiti.import("../lib/i18n.tsx");

test("观察与反思中英文文案准确说明来源、层级与只读边界", () => {
  const en = createTranslator("en");
  const zh = createTranslator("zh-CN");

  assert.equal(en("om_toggle"), "Observations & Reflections");
  assert.equal(zh("om_toggle"), "观察与反思");

  for (const t of [en, zh]) {
    assert.ok(t("om_sourceDescription").length > 20);
    assert.ok(t("om_observationsDescription").length > 8);
    assert.ok(t("om_reflectionsDescription").length > 8);
    assert.ok(t("om_projectionUnavailable").length > 8);
  }

  assert.match(en("om_sourceDescription"), /extensions/);
  assert.match(en("om_sourceDescription"), /not generated by Pidance/);
  assert.match(en("om_sourceDescription"), /without directly editing the Pi session/);
  assert.match(zh("om_sourceDescription"), /扩展写入/);
  assert.match(zh("om_sourceDescription"), /并非 Pidance 自动生成/);
  assert.match(zh("om_sourceDescription"), /不直接编辑 Pi 会话/);
});

test("ChatWindow 仅在已有会话加载完成后挂载观察与反思入口", () => {
  const source = readFileSync(fileURLToPath(new URL("./ChatWindow.tsx", import.meta.url)), "utf8");
  const decision = source.slice(
    source.indexOf("const omPanelElement"),
    source.indexOf("// 工作区历史"),
  );

  assert.match(decision, /loading \|\| !session \? null/);
  assert.match(decision, /<OmPanel/);
  assert.doesNotMatch(decision, /observationalMemory\?\.hasData \? null/);
});
