import assert from "node:assert/strict";
import test from "node:test";
import { createJiti } from "jiti";

const jiti = createJiti(import.meta.url);
const load = () => jiti.import("./file-editor-state.ts");
const input = (path, session = null, content = "a") => ({ filePath: path, sourceSessionId: session, content, language: "text", baseline: { mtimeMs: 1, size: content.length } });
const init = async (x = input("/x")) => { const m = await load(); return [m, m.fileEditorReducer(m.EMPTY_FILE_EDITOR_STATE, { type: "initialize", ...x })]; };

test("key isolates path and source session", async () => { const m = await load(); assert.notEqual(m.makeFileBufferKey("/x", "a"), m.makeFileBufferKey("/x", "b")); });
test("initialize only creates once and clean refreshes", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); const same = m.fileEditorReducer(s, { type: "initialize", ...input("/x", null, "b") }); assert.equal(m.getBuffer(s, key)?.content, "a"); assert.equal(m.getBuffer(same, key)?.content, "b"); });
test("dirty buffer rejects external content but records it", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); const dirty = m.fileEditorReducer(s, { type: "edit", key, content: "local", at: 1 }); const next = m.fileEditorReducer(dirty, { type: "initialize", ...input("/x", null, "remote") }); assert.equal(m.getBuffer(next, key)?.content, "local"); assert.equal(m.getBuffer(next, key)?.externalChange?.content, "remote"); });
test("typing merges at 500ms, force boundary does not", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); let x = m.fileEditorReducer(s, { type: "edit", key, content: "ab", at: 100 }); x = m.fileEditorReducer(x, { type: "edit", key, content: "abc", at: 600 }); assert.equal(m.getBuffer(x, key).past.length, 1); x = m.fileEditorReducer(x, { type: "edit", key, content: "abcd", at: 601, forceBoundary: true }); assert.equal(m.getBuffer(x, key).past.length, 2); });
test("history is capped and undo redo/new edit work", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); let x = s; for (let i = 1; i <= 60; i++) x = m.fileEditorReducer(x, { type: "edit", key, content: String(i), at: i * 1000 }); assert.equal(m.getBuffer(x, key).past.length, 50); x = m.fileEditorReducer(x, { type: "undo", key }); x = m.fileEditorReducer(x, { type: "redo", key }); x = m.fileEditorReducer(x, { type: "edit", key, content: "new", at: 100000 }); assert.equal(m.canRedo(m.getBuffer(x, key)), false); });
test("returning to saved content is clean", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); let x = m.fileEditorReducer(s, { type: "edit", key, content: "b", at: 1 }); x = m.fileEditorReducer(x, { type: "edit", key, content: "a", at: 1000, forceBoundary: true }); assert.equal(m.getBuffer(x, key).dirty, false); });
test("old save response is rejected and continued edit stays dirty", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); let x = m.fileEditorReducer(s, { type: "edit", key, content: "b", at: 1 }); x = m.fileEditorReducer(x, { type: "markSaving", key, requestId: "old" }); x = m.fileEditorReducer(x, { type: "edit", key, content: "c", at: 1000, forceBoundary: true }); x = m.fileEditorReducer(x, { type: "markSaving", key, requestId: "new" }); const old = m.fileEditorReducer(x, { type: "saveSuccess", key, requestId: "old", requestRevision: 1, savedContent: "b", baseline: { mtimeMs: 2, size: 1 } }); assert.equal(m.getBuffer(old, key).content, "c"); const done = m.fileEditorReducer(old, { type: "saveSuccess", key, requestId: "new", requestRevision: 2, savedContent: "c", baseline: { mtimeMs: 3, size: 1 } }); assert.equal(m.getBuffer(done, key).dirty, false); });
test("save conflict preserves draft and baseline", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); let x = m.fileEditorReducer(s, { type: "edit", key, content: "b", at: 1 }); x = m.fileEditorReducer(x, { type: "markSaving", key, requestId: "r" }); x = m.fileEditorReducer(x, { type: "saveConflict", key, requestId: "r", baseline: { mtimeMs: 9, size: 2 } }); assert.equal(m.getBuffer(x, key).content, "b"); assert.equal(m.getBuffer(x, key).baseline.mtimeMs, 9); });
test("discard, remove, dirty helper and immutability", async () => { const [m, s] = await init(); const key = m.makeFileBufferKey("/x"); const x = m.fileEditorReducer(s, { type: "edit", key, content: "b", at: 1 }); assert.equal(m.hasDirtyBuffers(x), true); assert.equal(m.hasDirtyBuffers(s), false); assert.equal(s.buffers[key].content, "a"); const clean = m.fileEditorReducer(x, { type: "discard", key }); assert.equal(m.getBuffer(clean, key).dirty, false); const removed = m.fileEditorReducer(clean, { type: "remove", key }); assert.equal(m.getBuffer(removed, key), undefined); });
